# Customize these with your info 

title: "çağatay tanyildiz" 
author: çağatay
description: "çağatay's personal website"
github: cagta
timezone: Europe/Amsterdam
url: https://cagataytanyildiz.com
language: en_US

# social images

favicon: /static/social-media-images/favicon-32x32.png
twitter: "@good-luck-twitter-existing-in-a-few-years"
social-media-image-url: /static/social-media-images/favicon-32x32.png
twitter-card-image: favicon-32x32.png
iOS-icon: /static/social-media-images/favicon-32x32.png

# leave these unless you are more familiar with jekyll settings

highlighter: rouge
markdown: kramdown
parse_block_html: false
show_drafts: true
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      blogpost: true
      layout: post
      og-type: article
      social-media-image: false
    
  -    
    scope:
      path: ""
      type: "pages"
    values:
      layout: page 
      social-media-image: false   

  -    
    scope:
      path: ""
      type: "no-index"
    values:
      layout: page
      no-index: true
      social-media-image: false

collections:
  pages:
    output: true
  no-index:
    output: true
  unlisted:
    output: true

plugins:
  - jekyll-feed
  - jekyll-linkpreview

feed:
  posts_limit: 25
  categories:
    - essays
    - notes
    - now
    - bookmarks

include:
  - .nojekyll